services:
    victoire_core.widget_sharethis_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: ShareThis }
    #alias to the form
    victoire.widget.form.sharethis:
        class: Victoire\Widget\ShareThisBundle\Form\WidgetShareThisType
        tags:
            - { name: form.type , alias: victoire_widget_form_sharethis}
