services:
    victoire_core.twig.widget_sharethis_manager:
        class: Victoire\Widget\ShareThisBundle\Widget\Manager\WidgetShareThisManager
        arguments: 
            - "@service_container"
            - "ShareThis"

    widget_sharethis_manager:
        alias: victoire_core.twig.widget_sharethis_manager
        
    #alias to the entity
    victoire.widget.sharethis:
        class: Victoire\Widget\ShareThisBundle\Entity\WidgetShareThis
    #alias to the form
    victoire.widget.form.sharethis:
        class: Victoire\Widget\ShareThisBundle\Form\WidgetShareThisType
        tags:
            - { name: form.type , alias: victoire_widget_form_sharethis}